version: "3.9"

services:
  users_backend:
    build:
      context: .
      args:
        - DEV=true
    container_name: users-ms
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_HOST: users_db
      DB_NAME: devdb
      DB_USER: devuser
      DB_PASS: changeme
      SECRET_KEY: dev_secret
      DEBUG: 1
    depends_on:
      - users_db
    networks:
      - users

  users_db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: changeme
    networks:
      - users


networks:
  users:
    name: users

volumes:
  dev-db-data: