---
name: Test and Lint

on:
  push:
    branches: ["users-dev"]
  pull_request:
    branches: ["users-master"]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker.dev/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker.dev-compose run --rm user_backend sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker.dev-compose run --rm user_backend sh -c "flake8"